import { readGameFile, writeJson, getString } from '../files.js';
import { toNumber } from '../to-number.js';

export async function monstersToJson(): Promise<Record<string, unknown>> {
  const table = await readGameFile('monsters');
  const monsters: Record<string, unknown> = {};

  for (const line of table) {
    if (getString(line[0]).trim() === '') continue;
    const code = getString(line[0] + ' ').trim();
    monsters[code] = {
      namestr: getString(line[5] + ' ').trim() || undefined,
      monstatsex: getString(line[6] + ' ').trim() || undefined,
      montype: getString(line[8] + ' ').trim() || undefined,
      spawn: getString(line[15] + ' ').trim() || undefined,
      el1mode: getString(line[198] + ' ').trim() || undefined,
      el1type: getString(line[199] + ' ').trim() || undefined,
      el2mode: getString(line[212] + ' ').trim() || undefined,
      el2type: getString(line[213] + ' ').trim() || undefined,
      sk1mode: getString(line[104] + ' ').trim() || undefined,
      sk2mode: getString(line[107] + ' ').trim() || undefined,
      sk3mode: getString(line[110] + ' ').trim() || undefined,
      sk4mode: getString(line[113] + ' ').trim() || undefined,
      sk5mode: getString(line[116] + ' ').trim() || undefined,
      sk6mode: getString(line[119] + ' ').trim() || undefined,
      sk7mode: getString(line[122] + ' ').trim() || undefined,
      sk8mode: getString(line[125] + ' ').trim() || undefined,
      minion1: getString(line[19] + ' ').trim() || undefined,
      minion2: getString(line[19] + ' ').trim() || undefined,
      code: getString(line[11] + ' ').trim() || undefined,
      treasureclass: getString(line[240] + ' ').trim() || undefined,
      treasureclassn: getString(line[247] + ' ').trim() || undefined,
      treasureclassh: getString(line[254] + ' ').trim() || undefined,
      treasureclasschamp: getString(line[241] + ' ').trim() || undefined,
      treasureclasschampn: getString(line[248] + ' ').trim() || undefined,
      treasureclasschamph: getString(line[255] + ' ').trim() || undefined,
      treasureclassunique: getString(line[242] + ' ').trim() || undefined,
      treasureclassuniquen: getString(line[249] + ' ').trim() || undefined,
      treasureclassuniqueh: getString(line[256] + ' ').trim() || undefined,
      treasureclassquest: getString(line[243] + ' ').trim() || undefined,
      treasureclassquestn: getString(line[250] + ' ').trim() || undefined,
      treasureclassquesth: getString(line[257] + ' ').trim() || undefined,
      treasureclassdesecrated: getString(line[244] + ' ').trim() || undefined,
      treasureclassdesecratedn: getString(line[251] + ' ').trim() || undefined,
      treasureclassdesecratedh: getString(line[258] + ' ').trim() || undefined,
      treasureclassdesecratedchamp: getString(line[245] + ' ').trim() || undefined,
      treasureclassdesecratedchampn: getString(line[252] + ' ').trim() || undefined,
      treasureclassdesecratedchamph: getString(line[259] + ' ').trim() || undefined,
      treasureclassdesecratedunique: getString(line[246] + ' ').trim() || undefined,
      treasureclassdesecrateduniquen: getString(line[253] + ' ').trim() || undefined,
      treasureclassdesecrateduniqueh: getString(line[260] + ' ').trim() || undefined,
      skill1: getString(line[103] + ' ').trim() || undefined,
      skill2: getString(line[106] + ' ').trim() || undefined,
      skill3: getString(line[109] + ' ').trim() || undefined,
      skill4: getString(line[112] + ' ').trim() || undefined,
      skill5: getString(line[115] + ' ').trim() || undefined,
      skill6: getString(line[118] + ' ').trim() || undefined,
      skill7: getString(line[121] + ' ').trim() || undefined,
      skill8: getString(line[124] + ' ').trim() || undefined,
      hcidx: toNumber(line[1]),
      velocity: toNumber(line[28]),
      run: toNumber(line[29]),
      level: toNumber(line[31]),
      leveln: toNumber(line[32]),
      levelh: toNumber(line[33]),
      isspawn: toNumber(line[76]),
      demon: toNumber(line[84]),
      ismelee: toNumber(line[77]),
      lundead: toNumber(line[82]),
      killable: toNumber(line[89]),
      switchai: toNumber(line[90]),
      drain: toNumber(line[127]),
      drainn: toNumber(line[128]),
      drainh: toNumber(line[129]),
      sk1lvl: toNumber(line[105]),
      sk2lvl: toNumber(line[108]),
      sk3lvl: toNumber(line[111]),
      sk4lvl: toNumber(line[114]),
      sk5lvl: toNumber(line[117]),
      sk6lvl: toNumber(line[120]),
      sk7lvl: toNumber(line[123]),
      sk8lvl: toNumber(line[126]),
      coldeffect: toNumber(line[130]),
      coldeffectn: toNumber(line[131]),
      coldeffecth: toNumber(line[132]),
      resdm: toNumber(line[133]),
      resdmn: toNumber(line[139]),
      resdmh: toNumber(line[145]),
      resma: toNumber(line[134]),
      resman: toNumber(line[140]),
      resmah: toNumber(line[146]),
      resfi: toNumber(line[135]),
      resfin: toNumber(line[141]),
      resfih: toNumber(line[147]),
      resli: toNumber(line[136]),
      reslin: toNumber(line[142]),
      reslih: toNumber(line[148]),
      resco: toNumber(line[137]),
      rescon: toNumber(line[143]),
      rescoh: toNumber(line[149]),
      respo: toNumber(line[138]),
      respon: toNumber(line[144]),
      respoh: toNumber(line[150]),
      damageregen: toNumber(line[151]),
      toblock: toNumber(line[155]),
      toblockn: toNumber(line[156]),
      toblockh: toNumber(line[157]),
      crit: toNumber(line[158]),
      minhp: toNumber(line[159]),
      maxhp: toNumber(line[160]),
      minhpn: toNumber(line[172]),
      maxhpn: toNumber(line[173]),
      minhph: toNumber(line[185]),
      maxhph: toNumber(line[186]),
      ac: toNumber(line[161]),
      acn: toNumber(line[174]),
      ach: toNumber(line[187]),
      exp: toNumber(line[162]),
      expn: toNumber(line[175]),
      exph: toNumber(line[188]),
      a1mind: toNumber(line[163]),
      a1mindn: toNumber(line[176]),
      a1mindh: toNumber(line[189]),
      a1maxd: toNumber(line[164]),
      a1maxdn: toNumber(line[177]),
      a1maxdh: toNumber(line[190]),
      a1th: toNumber(line[165]),
      a1thn: toNumber(line[178]),
      a1thh: toNumber(line[191]),
      a2mind: toNumber(line[166]),
      a2mindn: toNumber(line[179]),
      a2mindh: toNumber(line[192]),
      a2maxd: toNumber(line[167]),
      a2maxdn: toNumber(line[180]),
      a2maxdh: toNumber(line[193]),
      a2th: toNumber(line[168]),
      a2thn: toNumber(line[181]),
      a2thh: toNumber(line[194]),
      el1pct: toNumber(line[200]),
      el1mind: toNumber(line[201]),
      el1maxd: toNumber(line[202]),
      el1dur: toNumber(line[203]),
      el1pctn: toNumber(line[204]),
      el1mindn: toNumber(line[205]),
      el1maxdn: toNumber(line[206]),
      el1durn: toNumber(line[207]),
      el1pcth: toNumber(line[208]),
      el1mindh: toNumber(line[209]),
      el1maxdh: toNumber(line[210]),
      el1durh: toNumber(line[211]),
      el2pct: toNumber(line[214]),
      el2mind: toNumber(line[215]),
      el2maxd: toNumber(line[216]),
      el2dur: toNumber(line[217]),
      el2pctn: toNumber(line[218]),
      el2mindn: toNumber(line[219]),
      el2maxdn: toNumber(line[220]),
      el2durn: toNumber(line[221]),
      el2pcth: toNumber(line[222]),
      el2mindh: toNumber(line[223]),
      el2maxdh: toNumber(line[224]),
      el2durh: toNumber(line[225]),
      el3pct: toNumber(line[228]),
      el3mind: toNumber(line[229]),
      el3maxd: toNumber(line[230]),
      el3dur: toNumber(line[231]),
      el3pctn: toNumber(line[232]),
      el3mindn: toNumber(line[233]),
      el3maxdn: toNumber(line[234]),
      el3durn: toNumber(line[235]),
      el3pcth: toNumber(line[236]),
      el3mindh: toNumber(line[237]),
      el3maxdh: toNumber(line[238]),
      el3durh: toNumber(line[239]),
    };
  }

  await writeJson('monsters', monsters);
  return monsters;
}
