import { readGameFile, writeJson, getString } from '../files.js';
import { toNumber } from '../to-number.js';
import { getSkillId } from '../get-skill-id.js';

function stripQuotes(value: string | undefined): string | undefined {
  if (!value) return undefined;
  const str = String(value).trim();
  if (str.startsWith('"') && str.endsWith('"')) return str.slice(1, -1);
  return str || undefined;
}

export async function skillsToJson(): Promise<Record<string, unknown>> {
  const table = await readGameFile('skills');
  const skills: Record<string, unknown> = {};

  for (const line of table) {
    if (getString(line[1]).trim() === '') continue;
    const code = toNumber(line[1])!;
    skills[code] = {
      skill: getString(line[0]),
      charclass: getString(line[2]) || undefined,
      skilldesc: getString(line[3]) || undefined,
      srvmissilea: getString(line[18]) || undefined,
      srvmissileb: getString(line[19]) || undefined,
      srvmissilec: getString(line[20]) || undefined,
      aurastate: getString(line[24]) || undefined,
      summon: getString(line[77]) || undefined,
      pettype: getString(line[78]) || undefined,
      petmax: stripQuotes(line[79]) || undefined,
      sumsk1calc: getString(line[82]) || undefined,
      sumsk2calc: getString(line[84]) || undefined,
      sumsk3calc: getString(line[86]) || undefined,
      sumsk4calc: getString(line[88]) || undefined,
      sumsk5calc: getString(line[90]) || undefined,
      itypea1: getString(line[132]) || undefined,
      itypea2: getString(line[133]) || undefined,
      itypea3: getString(line[134]) || undefined,
      etypea1: getString(line[135]) || undefined,
      etypea2: getString(line[136]) || undefined,
      etypea3: getString(line[137]) || undefined,
      tohitcalc: getString(line[249]) || undefined,
      calc1: stripQuotes(line[210]) || undefined,
      calc2: stripQuotes(line[212]) || undefined,
      calc3: stripQuotes(line[214]) || undefined,
      calc4: stripQuotes(line[216]) || undefined,
      calc5: stripQuotes(line[218]) || undefined,
      calc6: stripQuotes(line[220]) || undefined,
      passivestate: getString(line[46]) || undefined,
      passivestat1: getString(line[49]) || undefined,
      passivestat2: getString(line[51]) || undefined,
      passivestat3: getString(line[53]) || undefined,
      passivestat4: getString(line[55]) || undefined,
      passivestat5: getString(line[57]) || undefined,
      passivestat6: getString(line[59]) || undefined,
      passivestat7: getString(line[61]) || undefined,
      passivestat8: getString(line[63]) || undefined,
      passivestat9: getString(line[65]) || undefined,
      passivestat10: getString(line[67]) || undefined,
      passivestat11: getString(line[69]) || undefined,
      passivestat12: getString(line[71]) || undefined,
      passivestat13: getString(line[73]) || undefined,
      passivestat14: getString(line[75]) || undefined,
      passivecalc1: stripQuotes(line[50]) || undefined,
      passivecalc2: stripQuotes(line[52]) || undefined,
      passivecalc3: stripQuotes(line[54]) || undefined,
      passivecalc4: stripQuotes(line[56]) || undefined,
      passivecalc5: stripQuotes(line[58]) || undefined,
      passivecalc6: stripQuotes(line[60]) || undefined,
      passivecalc7: stripQuotes(line[62]) || undefined,
      passivecalc8: stripQuotes(line[64]) || undefined,
      passivecalc9: stripQuotes(line[66]) || undefined,
      passivecalc10: stripQuotes(line[68]) || undefined,
      passivecalc11: stripQuotes(line[70]) || undefined,
      passivecalc12: stripQuotes(line[72]) || undefined,
      passivecalc13: stripQuotes(line[74]) || undefined,
      passivecalc14: stripQuotes(line[76]) || undefined,
      srvmissile: getString(line[15]) || undefined,
      anim: getString(line[142]) || undefined,
      monanim: getString(line[144]) || undefined,
      auralencalc: stripQuotes(line[26]) || undefined,
      aurarangecalc: stripQuotes(line[27]) || undefined,
      aurastat1: getString(line[28]) || undefined,
      aurastat2: getString(line[30]) || undefined,
      aurastat3: getString(line[32]) || undefined,
      aurastat4: getString(line[34]) || undefined,
      aurastat5: getString(line[36]) || undefined,
      aurastat6: getString(line[38]) || undefined,
      aurastatcalc1: stripQuotes(line[29]) || undefined,
      aurastatcalc2: stripQuotes(line[31]) || undefined,
      aurastatcalc3: stripQuotes(line[33]) || undefined,
      aurastatcalc4: stripQuotes(line[35]) || undefined,
      aurastatcalc5: stripQuotes(line[37]) || undefined,
      aurastatcalc6: stripQuotes(line[39]) || undefined,
      auratargetstate: getString(line[25]) || undefined,
      etype: getString(line[269]) || undefined,
      edmgsympercalc: getString(line[282]) || undefined,
      elensympercalc: getString(line[287]) || undefined,
      reqskill1: isNaN(Number(line[180])) ? await getSkillId(getString(line[180])) : toNumber(line[180]),
      reqskill2: isNaN(Number(line[181])) ? await getSkillId(getString(line[181])) : toNumber(line[181]),
      reqskill3: isNaN(Number(line[182])) ? await getSkillId(getString(line[182])) : toNumber(line[182]),
      id: code,
      delay: toNumber(line[187]),
      weapsel: toNumber(line[131]),
      reqlevel: toNumber(line[174]),
      maxlvl: toNumber(line[175]),
      restrict: toNumber(line[183]),
      leftskill: toNumber(line[189]),
      minmana: toNumber(line[195]),
      manashift: toNumber(line[196]),
      mana: toNumber(line[197]),
      lvlmana: toNumber(line[198]),
      aura: toNumber(line[201]),
      perdelay: toNumber(line[203]),
      passive: toNumber(line[207]),
      sumskill1: getString(line[81]) || undefined,
      sumskill2: getString(line[83]) || undefined,
      sumskill3: getString(line[85]) || undefined,
      sumskill4: getString(line[87]) || undefined,
      sumskill5: getString(line[89]) || undefined,
      param1: toNumber(line[222]),
      param2: toNumber(line[224]),
      param3: toNumber(line[226]),
      param4: toNumber(line[228]),
      param5: toNumber(line[230]),
      param6: toNumber(line[232]),
      param7: toNumber(line[234]),
      param8: toNumber(line[236]),
      param9: toNumber(line[238]),
      param10: toNumber(line[240]),
      param11: toNumber(line[242]),
      param12: toNumber(line[244]),
      aurafilter: toNumber(line[23]),
      tohit: toNumber(line[247]),
      levtohit: toNumber(line[248]),
      resultflags: toNumber(line[250]),
      hitshift: toNumber(line[254]),
      finishing: toNumber(line[204]),
      srcdam: toNumber(line[255]),
      emin: toNumber(line[270]),
      eminlev1: toNumber(line[271]),
      eminlev2: toNumber(line[272]),
      eminlev3: toNumber(line[273]),
      eminlev4: toNumber(line[274]),
      eminlev5: toNumber(line[275]),
      emax: toNumber(line[276]),
      emaxlev1: toNumber(line[277]),
      emaxlev2: toNumber(line[278]),
      emaxlev3: toNumber(line[279]),
      emaxlev4: toNumber(line[280]),
      emaxlev5: toNumber(line[281]),
      mindam: toNumber(line[256]),
      minlevdam1: toNumber(line[257]),
      minlevdam2: toNumber(line[258]),
      minlevdam3: toNumber(line[259]),
      minlevdam4: toNumber(line[260]),
      minlevdam5: toNumber(line[261]),
      maxdam: toNumber(line[262]),
      maxlevdam1: toNumber(line[263]),
      maxlevdam2: toNumber(line[264]),
      maxlevdam3: toNumber(line[265]),
      maxlevdam4: toNumber(line[266]),
      maxlevdam5: toNumber(line[267]),
      elen: toNumber(line[283]),
      elevlen1: toNumber(line[284]),
      elevlen2: toNumber(line[285]),
      elevlen3: toNumber(line[286]),
      costmult: toNumber(line[290]),
      costadd: toNumber(line[291]),
      enhanceable: toNumber(line[127]),
      srvstfunc: toNumber(line[4]),
      srvdofunc: toNumber(line[5]),
      seqnum: toNumber(line[145]),
    };
  }

  await writeJson('skills', skills);
  return skills;
}
