import { readGameFile, writeJson, getString } from '../files.js';
import { toNumber } from '../to-number.js';

function stripQuotes(value: string | undefined): string | undefined {
  if (!value) return undefined;
  const str = String(value).trim();
  if (str.startsWith('"') && str.endsWith('"')) return str.slice(1, -1);
  return str || undefined;
}

export async function skillDescToJson(): Promise<Record<string, unknown>> {
  const table = await readGameFile('skilldesc');
  const skillDesc: Record<string, unknown> = {};

  for (const line of table) {
    if (getString(line[0]) === '') continue;
    const code = getString(line[0] + ' ');
    skillDesc[code] = {
      strname: getString(line[7]),
      strshort: getString(line[8]),
      strlong: getString(line[9]),
      stralt: getString(line[10]),
      descmissile1: getString(line[24]) || undefined,
      descmissile2: getString(line[25]) || undefined,
      descmissile3: getString(line[26]) || undefined,
      srvmissileb: getString(line[19]) || undefined,
      srvmissilec: getString(line[20]) || undefined,
      summon: getString(line[77]) || undefined,
      pettype: getString(line[78]) || undefined,
      petmax: stripQuotes(line[79]),
      desctexta1: getString(line[28]) || undefined,
      desctexta2: getString(line[33]) || undefined,
      desctexta3: getString(line[38]) || undefined,
      desctexta4: getString(line[43]) || undefined,
      desctexta5: getString(line[48]) || undefined,
      desctexta6: getString(line[53]) || undefined,
      desctextb1: getString(line[29]) || undefined,
      desctextb2: getString(line[34]) || undefined,
      desctextb3: getString(line[39]) || undefined,
      desctextb4: getString(line[44]) || undefined,
      desctextb5: getString(line[49]) || undefined,
      desctextb6: getString(line[54]) || undefined,
      desccalca1: stripQuotes(line[30]),
      desccalca2: stripQuotes(line[35]),
      desccalca3: stripQuotes(line[40]),
      desccalca4: stripQuotes(line[45]),
      desccalca5: stripQuotes(line[50]),
      desccalca6: stripQuotes(line[55]),
      desccalcb1: stripQuotes(line[31]),
      desccalcb2: stripQuotes(line[36]),
      desccalcb3: stripQuotes(line[41]),
      desccalcb4: stripQuotes(line[46]),
      desccalcb5: stripQuotes(line[51]),
      desccalcb6: stripQuotes(line[56]),
      dsc2texta1: getString(line[58]) || undefined,
      dsc2texta2: getString(line[63]) || undefined,
      dsc2texta3: getString(line[68]) || undefined,
      dsc2texta4: getString(line[73]) || undefined,
      dsc2texta5: getString(line[78]) || undefined,
      dsc2textb1: getString(line[59]) || undefined,
      dsc2textb2: getString(line[64]) || undefined,
      dsc2textb3: getString(line[69]) || undefined,
      dsc2textb4: getString(line[74]) || undefined,
      dsc2textb5: getString(line[79]) || undefined,
      dsc2calca1: stripQuotes(line[60]),
      dsc2calca2: stripQuotes(line[65]),
      dsc2calca3: stripQuotes(line[70]),
      dsc2calca4: stripQuotes(line[75]),
      dsc2calca5: stripQuotes(line[80]),
      dsc2calcb1: stripQuotes(line[61]),
      dsc2calcb2: stripQuotes(line[66]),
      dsc2calcb3: stripQuotes(line[71]),
      dsc2calcb4: stripQuotes(line[76]),
      dsc2calcb5: stripQuotes(line[81]),
      dsc3texta1: getString(line[83]) || undefined,
      dsc3texta2: getString(line[88]) || undefined,
      dsc3texta3: getString(line[93]) || undefined,
      dsc3texta4: getString(line[98]) || undefined,
      dsc3texta5: getString(line[103]) || undefined,
      dsc3texta6: getString(line[108]) || undefined,
      dsc3texta7: getString(line[113]) || undefined,
      dsc3textb1: getString(line[84]) || undefined,
      dsc3textb2: getString(line[89]) || undefined,
      dsc3textb3: getString(line[94]) || undefined,
      dsc3textb4: getString(line[99]) || undefined,
      dsc3textb5: getString(line[104]) || undefined,
      dsc3textb6: getString(line[109]) || undefined,
      dsc3textb7: getString(line[114]) || undefined,
      dsc3calca1: stripQuotes(line[85]),
      dsc3calca2: stripQuotes(line[90]),
      dsc3calca3: stripQuotes(line[95]),
      dsc3calca4: stripQuotes(line[100]),
      dsc3calca5: stripQuotes(line[105]),
      dsc3calca6: stripQuotes(line[110]),
      dsc3calcb7: stripQuotes(line[115]),
      dsc3calcb1: stripQuotes(line[86]),
      dsc3calcb2: stripQuotes(line[91]),
      dsc3calcb3: stripQuotes(line[96]),
      dsc3calcb4: stripQuotes(line[101]),
      dsc3calcb5: stripQuotes(line[106]),
      dsc3calcb6: stripQuotes(line[111]),
      skillpage: toNumber(line[1]),
      skillrow: toNumber(line[2]),
      skillcolumn: toNumber(line[3]),
      listrow: toNumber(line[4]),
      iconcel: toNumber(line[5]),
      descdam: toNumber(line[11]),
      descatt: toNumber(line[23]),
      descline1: toNumber(line[27]),
      descline2: toNumber(line[32]),
      descline3: toNumber(line[37]),
      descline4: toNumber(line[42]),
      descline5: toNumber(line[47]),
      descline6: toNumber(line[52]),
      dsc2line1: toNumber(line[57]),
      dsc2line2: toNumber(line[62]),
      dsc2line3: toNumber(line[67]),
      dsc2line4: toNumber(line[72]),
      dsc2line5: toNumber(line[77]),
      dsc3line1: toNumber(line[82]),
      dsc3line2: toNumber(line[87]),
      dsc3line3: toNumber(line[92]),
      dsc3line4: toNumber(line[97]),
      dsc3line5: toNumber(line[102]),
      dsc3line6: toNumber(line[107]),
      dsc3line7: toNumber(line[112]),
    };
  }

  await writeJson('skillDesc', skillDesc);
  return skillDesc;
}
